import type { AnalysisResult } from "./types";

/**
 * Pre-computed example sentences to demonstrate the app without API calls.
 */
export const EXAMPLE_RESULTS: { label: string; result: AnalysisResult }[] = [
  {
    label: "She gave up smoking last year.",
    result: {
      id: "example-phrasal-verb",
      sentence: "She gave up smoking last year.",
      sentenceTranslation: "Вона кинула курити минулого року.",
      analyzedAt: new Date().toISOString(),
      words: [
        {
          id: "0",
          original: "She",
          lemma: "she",
          partOfSpeech: "pronoun",
          morphemes: [{ text: "she", type: "root", meaning: "female subject" }],
          isPunctuation: false,
          translation: "Вона",
        },
        {
          id: "1",
          original: "gave",
          lemma: "give",
          partOfSpeech: "phrasal_verb",
          morphemes: [
            { text: "g", type: "root", meaning: "transfer/yield" },
            { text: "ave", type: "ending", meaning: "past tense" },
          ],
          isPunctuation: false,
          translation: "кинула",
          groupId: "group-0",
          groupMeaning: "to stop doing something",
          groupTranslation: "кинути, припинити",
        },
        {
          id: "2",
          original: "up",
          lemma: "up",
          partOfSpeech: "phrasal_verb",
          morphemes: [
            { text: "up", type: "root", meaning: "completion particle" },
          ],
          isPunctuation: false,
          groupId: "group-0",
          groupMeaning: "to stop doing something",
          groupTranslation: "кинути, припинити",
        },
        {
          id: "3",
          original: "smoking",
          lemma: "smoking",
          partOfSpeech: "noun",
          morphemes: [
            { text: "smok", type: "root", meaning: "inhale smoke" },
            {
              text: "ing",
              type: "suffix",
              meaning: "forms nouns",
              translationUk: "утворює іменники",
            },
          ],
          isPunctuation: false,
          translation: "куріння",
        },
        {
          id: "4",
          original: "last",
          lemma: "last",
          partOfSpeech: "adjective",
          morphemes: [{ text: "last", type: "root", meaning: "most recent" }],
          isPunctuation: false,
          translation: "минулого",
        },
        {
          id: "5",
          original: "year",
          lemma: "year",
          partOfSpeech: "noun",
          morphemes: [
            { text: "year", type: "root", meaning: "12-month period" },
          ],
          isPunctuation: false,
          translation: "року",
        },
        {
          id: "6",
          original: ".",
          lemma: ".",
          partOfSpeech: "unknown",
          morphemes: [],
          isPunctuation: true,
        },
      ],
    },
  },
  {
    label: "It's a piece of cake for her.",
    result: {
      id: "example-idiom",
      sentence: "It's a piece of cake for her.",
      sentenceTranslation: "Для неї це простіше простого.",
      analyzedAt: new Date().toISOString(),
      words: [
        {
          id: "0",
          original: "It's",
          lemma: "it",
          partOfSpeech: "pronoun",
          morphemes: [
            { text: "It", type: "root", meaning: "impersonal subject" },
            { text: "'s", type: "ending", meaning: "contracted is" },
          ],
          isPunctuation: false,
        },
        {
          id: "1",
          original: "a",
          lemma: "a",
          partOfSpeech: "idiom",
          morphemes: [
            { text: "a", type: "root", meaning: "indefinite article" },
          ],
          isPunctuation: false,
          groupId: "group-0",
          groupMeaning: "something very easy",
          groupTranslation: "простіше простого",
        },
        {
          id: "2",
          original: "piece",
          lemma: "piece",
          partOfSpeech: "idiom",
          morphemes: [{ text: "piece", type: "root", meaning: "portion/part" }],
          isPunctuation: false,
          groupId: "group-0",
          groupMeaning: "something very easy",
          groupTranslation: "простіше простого",
        },
        {
          id: "3",
          original: "of",
          lemma: "of",
          partOfSpeech: "idiom",
          morphemes: [{ text: "of", type: "root", meaning: "belonging to" }],
          isPunctuation: false,
          groupId: "group-0",
          groupMeaning: "something very easy",
          groupTranslation: "простіше простого",
        },
        {
          id: "4",
          original: "cake",
          lemma: "cake",
          partOfSpeech: "idiom",
          morphemes: [{ text: "cake", type: "root", meaning: "baked dessert" }],
          isPunctuation: false,
          groupId: "group-0",
          groupMeaning: "something very easy",
          groupTranslation: "простіше простого",
        },
        {
          id: "5",
          original: "for",
          lemma: "for",
          partOfSpeech: "preposition",
          morphemes: [{ text: "for", type: "root", meaning: "intended to" }],
          isPunctuation: false,
          translation: "для",
        },
        {
          id: "6",
          original: "her",
          lemma: "she",
          partOfSpeech: "pronoun",
          morphemes: [{ text: "her", type: "root", meaning: "female object" }],
          isPunctuation: false,
          translation: "неї",
        },
        {
          id: "7",
          original: ".",
          lemma: ".",
          partOfSpeech: "unknown",
          morphemes: [],
          isPunctuation: true,
        },
      ],
    },
  },
  {
    label: "The uncomfortable realization transformed her understanding.",
    result: {
      id: "example-morphemes",
      sentence: "The uncomfortable realization transformed her understanding.",
      sentenceTranslation: "Некомфортне усвідомлення змінило її розуміння.",
      analyzedAt: new Date().toISOString(),
      words: [
        {
          id: "0",
          original: "The",
          lemma: "the",
          partOfSpeech: "determiner",
          morphemes: [
            { text: "the", type: "root", meaning: "definite article" },
          ],
          isPunctuation: false,
        },
        {
          id: "1",
          original: "uncomfortable",
          lemma: "uncomfortable",
          partOfSpeech: "adjective",
          morphemes: [
            {
              text: "un",
              type: "prefix",
              meaning: "negation",
              translationUk: "заперечення",
            },
            { text: "comfort", type: "root", meaning: "ease, solace" },
            {
              text: "able",
              type: "suffix",
              meaning: "capable of",
              translationUk: "здатність",
            },
          ],
          isPunctuation: false,
          translation: "некомфортне",
        },
        {
          id: "2",
          original: "realization",
          lemma: "realization",
          partOfSpeech: "noun",
          morphemes: [
            { text: "real", type: "root", meaning: "actual, true" },
            {
              text: "iz",
              type: "suffix",
              meaning: "forms verbs",
              translationUk: "утворює дієслова",
            },
            {
              text: "ation",
              type: "suffix",
              meaning: "forms nouns",
              translationUk: "утворює іменники",
            },
          ],
          isPunctuation: false,
          translation: "усвідомлення",
        },
        {
          id: "3",
          original: "transformed",
          lemma: "transform",
          partOfSpeech: "verb",
          morphemes: [
            {
              text: "trans",
              type: "prefix",
              meaning: "across, beyond",
              translationUk: "через, крізь",
            },
            { text: "form", type: "root", meaning: "shape" },
            { text: "ed", type: "ending", meaning: "past tense" },
          ],
          isPunctuation: false,
          translation: "змінило",
        },
        {
          id: "4",
          original: "her",
          lemma: "she",
          partOfSpeech: "pronoun",
          morphemes: [
            { text: "her", type: "root", meaning: "female possessive" },
          ],
          isPunctuation: false,
          translation: "її",
        },
        {
          id: "5",
          original: "understanding",
          lemma: "understanding",
          partOfSpeech: "noun",
          morphemes: [
            {
              text: "under",
              type: "prefix",
              meaning: "beneath",
              translationUk: "під",
            },
            { text: "stand", type: "root", meaning: "endure, grasp" },
            {
              text: "ing",
              type: "suffix",
              meaning: "forms nouns",
              translationUk: "утворює іменники",
            },
          ],
          isPunctuation: false,
          translation: "розуміння",
        },
        {
          id: "6",
          original: ".",
          lemma: ".",
          partOfSpeech: "unknown",
          morphemes: [],
          isPunctuation: true,
        },
      ],
    },
  },
];
